Secure log in and sign up - Backend part
seomasha/abh-internship-cinemaapp pull request #15
Opened 2024-11-20 08:27 UTC by seomasha

- Coming soon

2024-11-20 12:10 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/config/SecurityConfig.java
> +                //.addFilterBefore(new JwtAuthenticationFilter(jwtUtil), UsernamePasswordAuthenticationFilter.class) Dodat ce se poslije da se zastite rute
What about this comment? You already have some routes to protect like create movie for example.

2024-11-20 12:22 UTC, seomasha commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/config/SecurityConfig.java
> +                //.addFilterBefore(new JwtAuthenticationFilter(jwtUtil), UsernamePasswordAuthenticationFilter.class) Dodat ce se poslije da se zastite rute
I added this because of testing purposes. I had protected the routes but then when I send a request to any route I always get 403 forbidden. So I removed the code I had so I could make sure that I could log in with my credentials.

2024-11-20 12:23 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/utils/JwtAuthenticationFilter.java
> +                    final String username = jwtUtil.extractEmail(token);
Are you using the username anywhere? And let's think about how to make this if statement a little nicer. There is a lot of nesting.

2024-11-20 12:49 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/service/CustomUserDetailsService.java
> +}
new line

2024-11-20 12:53 UTC, ivanazirojevic-abh requested changes
Please address some comments and write tests for services and utils. Make sure all other tests pass.

2024-11-20 13:36 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/config/SecurityConfig.java
> +                //.addFilterBefore(new JwtAuthenticationFilter(jwtUtil), UsernamePasswordAuthenticationFilter.class) Dodat ce se poslije da se zastite rute
Okay. Makes sense. In this case, in the application properties you can add:
```
spring:
  profiles:
    active: local # Set to 'dev' or  'prod' in respective environments.
```

And use it to disable auth for "local"
```
    @Value("${spring.profiles.active:}")
    private String activeProfile;
```

```
       if ("local".equals(activeProfile)) {
            http.csrf().disable()
               .authorizeHttpRequests(auth -> auth.anyRequest().permitAll());
        } else {
            http.csrf().enable()
               .authorizeHttpRequests(auth -> auth.anyRequest().authenticated())
               .formLogin();
        }
```

2024-11-21 08:07 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/config/SecurityConfig.java
> +        if ("dev".equals(profile)) {
Let's use "local" because on dev envs you usually still want auth.

2024-11-21 08:13 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/utils/JwtAuthenticationFilter.java
> +                    jwtUtil.validateToken(token, user);
What happens if the token is invalid? Are you doing anything apart logging the error?

2024-11-21 08:20 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/utils/JwtUtil.java
> +    private long expirationTime = 1000 * 60 * 60; // Final keyword je izostavljen kako bi se
Make it final. Use mocks in tests. Code should not depend on tests. Please leave comments in English 😄

2024-11-21 08:20 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/test/java/com/abhinternship/CinemaApp/service/CustomUserDetailsServiceTest.java
> +        User user = new User();
final

2024-11-21 08:23 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/test/java/com/abhinternship/CinemaApp/utils/JwtUtilTest.java
> +        String token = jwtUtil.generateToken(user);
final

2024-11-21 08:24 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/test/java/com/abhinternship/CinemaApp/utils/JwtUtilTest.java
> +        boolean isExpired = jwtUtil.isTokenExpired(token);
You don't need the variable. Just do `assertFalse(jwtUtil.isTokenExpired(token));`

2024-11-21 08:30 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/config/SecurityConfig.java
> +                                .requestMatchers(HttpMethod.GET, "/api/v1/movies").permitAll()
Think about all routes you want to allow. Maybe venues or something like that. Also don't repeat the "/api/v1/" part

2024-11-26 11:50 UTC, ivanazirojevic-abh approved these changes
LGTM!

2024-11-26 11:51 UTC, merged