Login and signup - FE & BE Functionality
seomasha/abh-internship-cinemaapp pull request #18
Opened 2024-11-28 15:55 UTC by seomasha

- Implement account registration with email and password
- Validating email and password
- Implementing log in functionality with email and password
- Implementing password reset functionality
- Adding unit tests for service methods

2024-11-29 08:56 UTC, ivanazirojevic-abh commented on cinemaapp_frontend/src/components/AuthForm.jsx
>      const response = await otpService.create({ email: email });
For security reasons you cannot have the correct otp saved in frontend. Have in mind that the users have access to any data you store locally through the console. If you open the browser tools you can even set debugger break points and evaluate any step you want. That way the user could take the value from there and bypass the email verification. You will need to have verify otp method on the backend and just send the input. Make sure to have small loading spinner while the otp is being validated so user knows they have to wait a little.

2024-11-29 08:58 UTC, ivanazirojevic-abh commented on cinemaapp_frontend/src/components/AuthForm.jsx
> +        }, 3000);
why do we have this timeout?

2024-11-29 08:59 UTC, seomasha commented on cinemaapp_frontend/src/components/AuthForm.jsx
> +        }, 3000);
There is like a small animation that says Sign in successful.

2024-11-29 09:04 UTC, ivanazirojevic-abh commented on cinemaapp_frontend/src/components/AuthForm.jsx
> +        }, 3000);
Let's add a comment above the timeout explaining it a bit just because it's not very obvious right away why it's there.

2024-11-29 09:05 UTC, ivanazirojevic-abh requested changes
Validate otp needs to be in the backend for security reasons.

2024-11-29 10:01 UTC, ivanazirojevic-abh commented on cinemaapp_frontend/src/components/AuthForm.jsx
> +    if (response && validateEmail(email) && emailExists) {
Why do we have this if statement? When otp.create() is called the backend should validate and send the email. Error handling from apiService should handle the errors.

2024-11-29 10:03 UTC, ivanazirojevic-abh commented on cinemaapp_frontend/src/components/AuthForm.jsx
>      const response = await otpService.create({ email: email });
Rename method to send.

2024-11-29 10:25 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/service/OtpService.java
>  public class OtpService {
Combine verify and validate methods from this service so there is only one.

2024-11-29 10:27 UTC, ivanazirojevic-abh commented on cinemaapp_frontend/src/components/AuthForm.jsx
>      if (response === "OTP Verified!") {
Can you use the status instead of the message? Maybe this text changes in the future and breaks the app.

2024-12-02 06:53 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/rest/UserController.java
> +    @GetMapping("/email/{email}")
It's not a good practice to keep an email in the path. It might lead to url encoding issues and it might be a security risk to expose the email like this. If you want to log some error, you will have user emails in the logs.
Let's have it like this:
```
@GetMapping("/email")
public ResponseEntity<?> getByEmail(@RequestParam String email) {
}
```

2024-12-02 06:59 UTC, ivanazirojevic-abh approved these changes
Please address one small comment and then this PR can be merged.

2024-12-02 07:03 UTC, merged