Checkout & payment integration
seomasha/abh-internship-cinemaapp pull request #21
Opened 2024-12-05 11:48 UTC by seomasha

2024-12-06 09:11 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/utils/ErrorHandler.java
> +        return new ResponseEntity<>(buildErrorResponse("Stripe error: " + ex.getMessage(), HttpStatus.BAD_REQUEST), HttpStatus.BAD_REQUEST);
Instead of "Stripe error" you can have it as "Payment processing error". Users don't need to know which libraries we use on backend. Info like this should be logged.

2024-12-06 09:18 UTC, ivanazirojevic-abh commented on cinemaapp_frontend/src/services/paymentService.js
> +    const response = await request(`${PAYMENT_ENDPOINT}/create`, {
create method should be already there from apiService.

2024-12-06 09:19 UTC, ivanazirojevic-abh commented on cinemaapp_frontend/src/services/ticketService.js
> +      `${TICKET_ENDPOINT}/reserved-seats?projectionId=${projectionId}&date=${date}`
Nothing to fix but be aware of character encoding in url. it could potentially mess up the date depending on the format.

2024-12-06 09:20 UTC, seomasha commented on cinemaapp_frontend/src/services/paymentService.js
> +    const response = await request(`${PAYMENT_ENDPOINT}/create`, {
The create method from the apiService would create an entry in the payments table in the database. This only creates an intent specific to Stripe that is used to verify the payment.

2024-12-06 09:21 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/rest/PaymentController.java
> +        emailService.sendPaymentMail(email, subject);
Does stripe require you to have intent and confirmation? if yes, why is there no logic for stripe here?

2024-12-06 09:24 UTC, seomasha commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/rest/PaymentController.java
> +        emailService.sendPaymentMail(email, subject);
This endpoint is mainly for sending the confirmation email. On the frontend side, the handleConfirmPayment method (Checkout.jsx) uses the stripe.confirmCardPayment for the actual confirmation of the payment.

2024-12-06 09:27 UTC, ivanazirojevic-abh commented on cinemaapp_frontend/src/pages/Checkout.jsx
> +      amount: price * 100 * 0.51, // Since Stripe doesn't support BAM, I use euros and convert them into BAM
if you are going to do this conversion, make sure to have up to date conversion rate. Research api from authorised sources and fetch the rate from them.

2024-12-06 09:28 UTC, ivanazirojevic-abh commented on cinemaapp_frontend/src/pages/Checkout.jsx
> +      console.error("Stripe or Elements not loaded");
Show "Something went wrong" or  "Payment failed" to the user.

2024-12-06 09:29 UTC, ivanazirojevic-abh commented on cinemaapp_frontend/src/pages/Checkout.jsx
> +      console.error("Payment confirmation failed", confirmError.message);
Make sure if something goes wrong, the user gets notified. If you just log the error, they think everything is okay.

2024-12-06 09:33 UTC, ivanazirojevic-abh commented on cinemaapp_frontend/src/services/paymentService.js
> +    const response = await request(`${PAYMENT_ENDPOINT}/create`, {
Can you rename the endpoint to create-intent

2024-12-06 13:00 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/rest/PaymentController.java
> +        emailService.sendPaymentMail(email, subject);
change the endpoint to send-confirmation-email

2024-12-06 13:01 UTC, seomasha commented on cinemaapp_frontend/src/services/paymentService.js
> +    const response = await request(`${PAYMENT_ENDPOINT}/create`, {
Will do!

2024-12-06 13:01 UTC, seomasha commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/rest/PaymentController.java
> +        emailService.sendPaymentMail(email, subject);
Done!

2024-12-06 13:05 UTC, ivanazirojevic-abh approved these changes
LGTM!

2024-12-09 11:30 UTC, ivanazirojevic-abh commented on cinemaapp_frontend/src/pages/Checkout.jsx
> +      alert("Deleted card succesfully");
Why are you using alert? You have toast messages service

2024-12-09 11:31 UTC, ivanazirojevic-abh commented on cinemaapp_frontend/src/pages/Checkout.jsx
> +      setSelectedCardId(null);
setSelectedCardId(cardId === selectedCardId? null : cardId)

2024-12-09 18:13 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/service/PaymentService.java
> +        boolean isDuplicate = existingPaymentMethods.stream()
final

2024-12-09 18:15 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/service/TicketServiceImpl.java
> +        String seats = String.join(",", seatNos);
final

2024-12-09 18:15 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/service/TicketServiceImpl.java
> +        Ticket ticket = new Ticket();
final

2024-12-09 18:17 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/service/TicketServiceImpl.java
> +        return seatPrices.get("regular");
Looks like this logic would work:

```
 if (seatNo.startsWith("G") || seatNo.startsWith("H")) {
            return seatPrices.get("vip");
        } else if (seatNo.startsWith("I")) {
            return seatPrices.get("love");
        }
        return seatPrices.get("regular");
```

2024-12-09 18:19 UTC, ivanazirojevic-abh commented on cinemaapp_frontend/src/pages/Checkout.jsx
> +      ToastService.info("Deleted card.");
If this is success confirmation then it should be .success(). Usually info is just to tell the user some additional info. Please also make the message a little better like `Card deleted successfully!`

2024-12-09 18:23 UTC, ivanazirojevic-abh requested changes
Please address small comments but otherwise looks much better.

2024-12-10 09:24 UTC, ivanazirojevic-abh approved these changes
LGTM!

2024-12-10 09:25 UTC, merged