Admin panel - FE
seomasha/abh-internship-cinemaapp pull request #23
Opened 2024-12-10 04:41 UTC by seomasha

- Created entire frontend for admin panel
- Added validation for fields

2024-12-10 09:28 UTC, ivanazirojevic-abh commented on cinemaapp_frontend/src/components/NavBar.jsx
> +              {role === "admin" && (
Do you have  any kind of route protection? If I manually type in a url for /admin and I am not one, is it going to let me  access the page?

2024-12-10 09:35 UTC, seomasha commented on cinemaapp_frontend/src/components/NavBar.jsx
> +              {role === "admin" && (
I will make sure the access will be restricted for non-admin roles,  I just started working on this.

2024-12-11 13:44 UTC, ivanazirojevic-abh commented on cinemaapp_frontend/src/components/MovieTable.jsx
> +    return "Sead";
It's a good name but I don't think it's appropriate value here :D

2024-12-11 13:59 UTC, ivanazirojevic-abh commented on cinemaapp_frontend/src/pages/AdminPanel.jsx
> +    isValid &= !setError(
I would stay away from bitwise operators because for many people it would be much harder to understand this code. They can sometimes be a little unpredictable too and cause bugs. I would rather suggest you write something like this
```
if (!movieName) {
  setError(true, setMovieNameError, "You should enter a movie name.");
  isValid = false;
}
```
Maybe you can think about something better.

2024-12-11 14:04 UTC, ivanazirojevic-abh commented on cinemaapp_frontend/src/pages/AdminPanel.jsx
> +    isValid &= !setError(
I see a lot of code repetition here. Maybe you can do something like this:
```
const validationRules = [
{
    condition: !movieName,
    errorMessage: "You should enter a movie name."
},
{
    condition: !pgRating,
    errorMessage: "You should enter a PG rating."
},
...
]

```
And then you can use a loop to evaluate each rule and set the errors if needed.

2024-12-11 14:05 UTC, ivanazirojevic-abh commented on cinemaapp_frontend/src/pages/AdminPanel.jsx
> +    isValid &= !setError(
Same comment as above.

2024-12-11 14:07 UTC, ivanazirojevic-abh commented on cinemaapp_frontend/src/pages/AdminPanel.jsx
> +      setCheckedMovies((prev) => prev.filter((id) => id !== movieId));
Can you try to make it shorter like this:
`setCheckedMovies((prev) => (isChecked ? [...prev, movieId] : prev.filter((id) => id !== movieId)));
`

2024-12-11 14:11 UTC, ivanazirojevic-abh requested changes
Please address few syntax comments, but otherwise it's looking great. Tons of work done. Amazing as always!

2024-12-11 14:50 UTC, seomasha commented on cinemaapp_frontend/src/components/MovieTable.jsx
> +    return "Sead";
Oops :D

2024-12-12 09:27 UTC, ivanazirojevic-abh approved these changes
LGTM!

2024-12-12 10:14 UTC, merged