Home page - Backend implementation
seomasha/abh-internship-cinemaapp pull request #9
Opened 2024-10-23 16:21 UTC by seomasha

- Connection the frontend and backend of HomePage
- Creating repositories for Movie, Projection and Venue
- Creating services for Movie, Projection and Venue
- Creating controllers for Movie, Projection and Venue
- Showing released movies in Currently Showing list and unreleased in Upcoming movies
- Fetching movies that are currently showing and which are upcoming based on the selected Venue

2024-10-25 09:20 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/config/SecurityConfig.java
> +        config.setAllowedOrigins(List.of("http://localhost:5173"));
Let's have this as an env variable instead of hardcoding it here.

2024-10-25 09:24 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/rest/MovieController.java
> +        List<Movie> movies = movieService.findAllMovies();
Make sure all variables in this file are final.

2024-10-25 09:27 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/rest/MovieController.java
> +        List<Movie> movies = projections.stream()
Logic like this should be kept in the service. Controllers should only deal with requests and responses.

2024-10-25 09:29 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/rest/MovieController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body(savedMovie);
There needs to be more error handling. What if the movie cannot be created for any reason? Make sure you give back descriptive errors for your frontend.

2024-10-25 09:34 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/rest/MovieController.java
> +        return ResponseEntity.noContent().build();
Error handling for id that does not exist. I know you are planning to validate this on frontend but your backend should not depend on the frontend validation. 

If everything is okay respond something like this:
```
  return ResponseEntity.ok(
                Response.builder()
                        .withSuccess(true)
                        .withMessage("Movie deleted successfully.")
                        .build()
        );
```

2024-10-25 09:35 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/rest/MovieController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body(savedMovie);
You dont have to respond with the full movie body. Id is enough. Example:
```
        return ResponseEntity.ok(
                Response.builder()
                        .withSuccess(true)
                        .withMessage("New movie successfully created.")
                        .withData(movieId)
                        .build()
        );
```

2024-10-25 09:37 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/rest/ProjectionController.java
> +        List<Projection> projections = projectionService.findAllByVenueId(venueId);
Make all variables in this file final.

2024-10-25 09:37 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/rest/ProjectionController.java
> +        return ResponseEntity.ok(projections);
Handle error when venueId does not exist.

2024-10-25 09:39 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/rest/VenueController.java
> +        Venue savedVenue = venueService.saveVenue(venue);
final keyword for variables in the whole file.

2024-10-25 09:40 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/rest/VenueController.java
> +        Venue savedVenue = venueService.saveVenue(venue);
Error handling and more detailed responses for all these apis.

2024-10-25 09:41 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/service/MovieServiceImpl.java
> +    public void deleteMovie(Long id) {
Make all parameters final in this file.

2024-10-28 08:37 UTC, ivanazirojevic-abh commented on cinemaapp_backend/.gitignore
> +.DS_Store
new line

2024-10-28 08:40 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/rest/MovieController.java
> +        try {
Instead of wrapping every controller with try/catch blocks you can use @ControllerAdvice annotation. Something like this:
```
@ControllerAdvice
public class GlobalExceptionHandler {

    @ExceptionHandler(ResourceNotFoundException.class)
    public ResponseEntity<String> handleResourceNotFound(ResourceNotFoundException ex) {
        return ResponseEntity.status(HttpStatus.NOT_FOUND).body(ex.getMessage());
    }

    // jos handlera...
}
```

2024-10-28 08:41 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/rest/MovieController.java
> +            List<Movie> movies = movieService.findAllMovies();
final keyword

2024-10-28 08:41 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/rest/MovieController.java
> +            List<Movie> movies = movieService.findMoviesByVenueId(venueId);
final keyword

2024-10-28 08:42 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/rest/ProjectionController.java
> +            List<Projection> projections = projectionService.findAllProjections();
final

2024-10-28 08:42 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/rest/ProjectionController.java
> +            List<Projection> projections = projectionService.findAllByVenueId(venueId);
final keyword

2024-10-28 08:51 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/utils/ErrorHandler.java
> +    private Map<String, Object> buildErrorResponse(final String message, final HttpStatus status) {
Keep the helper methods below the important methods that use them. When a developer opens this file, they are most likely searching to see how the error methods are implemented. They probably don't care about this method right away.

2024-10-28 08:53 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/rest/MovieController.java
> +        try {
I have just seen that you have implemented the error handler therefore you don't need these try/catch blocks. Spring boot should handle it on its own. Please test this by forcing a couple of errors.

2024-10-28 12:44 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/rest/ProjectionController.java
> +            return ResponseEntity.ok(new ArrayList<>());
Can you return the empty list from the service?

2024-10-28 12:45 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/rest/VenueController.java
> +        return ResponseEntity.noContent().build();
In these cases you can return a success message like "Venue with id {} successfully deleted." Just to indicate to anybody using this API that the action was successful. Make sure ok status code is also returned.

2024-10-28 12:47 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/utils/ErrorHandler.java
> +        StringBuilder message = new StringBuilder("Validation failed: ");
final

2024-10-28 12:47 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/utils/ErrorHandler.java
> +        Map<String, Object> errorDetails = new HashMap<>();
final

2024-10-28 12:50 UTC, ivanazirojevic-abh commented on cinemaapp_frontend/src/components/Hero.jsx
> +      setIsSmallScreen(window.innerWidth <= 768);
Can we have a global object with screen sizes that you can share among multiple components. Let's avoid magic numbers.

2024-10-28 12:55 UTC, ivanazirojevic-abh commented on cinemaapp_frontend/src/pages/Home.jsx
> +      const movies = await movieService.getAll();
Are you fetching all movies at once? Let's not do this on the frontend side. We need our backend to process the data and return currently showing or upcoming movies. If we have many movies in our database this will make problems like slow loading times or even error due to too much data.

2024-10-28 12:57 UTC, ivanazirojevic-abh commented on cinemaapp_frontend/src/pages/Home.jsx
> +      const movies = await movieService.getAll();
There should be filtering API on the backend side. Maybe you can use the same endpoint for filtering that you will have on other pages. Just make sure you can give it a parameter for filtering from the frontend side.

2024-10-28 12:59 UTC, ivanazirojevic-abh commented on cinemaapp_frontend/src/pages/Home.jsx
> +      const movies = await movieService.getAll();
Pagination should be used.

2024-10-28 12:59 UTC, ivanazirojevic-abh commented on cinemaapp_frontend/src/pages/Home.jsx
> +        const projections = await projectionService.getProjectionsByVenueId(
Same here, don't fetch all at once, filter on backend and use pagination.

2024-10-28 13:03 UTC, ivanazirojevic-abh commented on cinemaapp_frontend/src/services/apiService.js
> +export const BASE_URL = "http://localhost:8080/api/v1";
If you were to deploy this, you would need to change the code and then it would no longer work on local so let's keep these values as env variables.

2024-10-28 13:03 UTC, ivanazirojevic-abh commented on cinemaapp_frontend/src/services/apiService.js
> +export const BASE_URL = "http://localhost:8080/api/v1";
And also you wouldn't be able to have different environments like dev, qa, staging, prod.

2024-10-28 13:05 UTC, ivanazirojevic-abh commented on cinemaapp_frontend/src/styles/SearchBar.css
> +
New line

2024-10-28 13:06 UTC, ivanazirojevic-abh requested changes
You are currently doing most of the heavy logic on the frontend side like fetching all movies and then filtering them to find searching and upcoming. Let's try to keep the logic on the backend as much as possible.

2024-10-29 09:46 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/repository/MovieRepository.java
> +    Page<Movie> findMoviesByProjectionDateRange(@Param("startDate") LocalDate startDate, @Param("endDate") LocalDate endDate, Pageable pageable);
Can you check if the JPA repository has a method that supports querying by date range so you dont't need to write query manually?

2024-10-29 09:46 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/repository/MovieRepository.java
> +    Page<Movie> findUpcomingMovies(@Param("endDate") LocalDate endDate, Pageable pageable);
Same here, try to investigate what can be done with JPA alone.

2024-10-29 09:50 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/rest/MovieController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body(savedMovie);
Let's not return the whole movie, just the id. Frontend should already have the other info since it sent the request for creation. We should always try to send the least amount of data possible for performance and security purposes.

2024-10-29 09:53 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/service/MovieServiceImpl.java
> +    public List<Movie> findCurrentlyShowingMovies(int page, int size) {
final keyword for parameters

2024-10-29 10:02 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/service/MovieServiceImpl.java
> +        final LocalDate endDate = LocalDate.now().plusDays(10);
You don't need to change anything here now but just so you know, when you are dealing with dates it is often the case that the client is not in the same timezone as the server because when you use some hosting service, the physical machine could be for example in USA. This means you might send incorrect data to the client with offset up to one day.
Have that in mind for the future. You should take the timezone from the client so you can filter correctly.

2024-10-29 10:02 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/service/MovieServiceImpl.java
> +    public List<Movie> findUpcomingMovies(int page, int size) {
final params

2024-10-29 10:04 UTC, seomasha commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/repository/MovieRepository.java
> +    Page<Movie> findMoviesByProjectionDateRange(@Param("startDate") LocalDate startDate, @Param("endDate") LocalDate endDate, Pageable pageable);
I tried using it with JPA alone but I don't get the correct response back, so that is why I left the @Query.

2024-10-29 10:06 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/service/MovieServiceImpl.java
> +        final List<Movie> allMovies = movieRepository.findAll();
Let's avoid querying all movies. Imagine we have couple of thousands of them. It will be slow. I'd rather you put a limit to querying.
Is this for the carousel? If yes let's take three from the currently showing. Just send the request for fetching currently showing movies and limit it to 3.

2024-10-29 10:06 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/service/ProjectionServiceImpl.java
> +    public Map<String, List<Movie>> getMoviesByVenue(Venue venue, int page, int size) {
final params

2024-10-29 10:09 UTC, ivanazirojevic-abh commented on cinemaapp_frontend/.gitignore
> +.env
new line

2024-10-29 10:15 UTC, seomasha commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/service/MovieServiceImpl.java
> +        final LocalDate endDate = LocalDate.now().plusDays(10);
Will do!

2024-10-29 16:44 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/rest/MovieController.java
> +        return movieService.findMovieById(id).map(ResponseEntity::ok).orElseThrow(() -> new ResourceNotFoundException("Movie not found with id: " + id));
It's a common practice to keep lines shorter than 120 characters so it is fully visible on most screens.
Please break it up like this:
```
return movieService.findMovieById(id)
                .map(ResponseEntity::ok)
                .orElseThrow(() -> new ResourceNotFoundException("Movie not found with id: " + id));
```

2024-10-29 16:44 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/rest/MovieController.java
> +        return movieService.findMovieById(id).map(ResponseEntity::ok).orElseThrow(() -> new ResourceNotFoundException("Movie not found with id: " + id));
Please check other lines in this file as well.

2024-10-29 16:46 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/rest/MovieController.java
> +        List<Movie> currentlyShowingMovies = movieService.findCurrentlyShowingMovies(page, size);
final keyword

2024-10-29 16:47 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/rest/MovieController.java
> +        List<Movie> currentlyShowingMovies = movieService.findCurrentlyShowingMovies(page, size);
Check all variables in this file too.

2024-10-29 16:49 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/service/MovieServiceImpl.java
> +        final Page<Movie> currentlyShowingMoviesPage = movieRepository.findByProjectionStartDateBeforeAndProjectionEndDateAfter(today.plusDays(10), today, pageable);
Try to break this line in some way to keep it shorter than 120chars even though the method name is lengthy.

2024-10-30 08:51 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/service/MovieServiceImpl.java
> +        final Page<Projection> projectionPage = projectionRepository.findAllByVenueId(venue, PageRequest.of(page, size));
Let's have a repository method that will deal with filtering by venues and dates so you don't have to loop over them and complicate logic.

2024-10-31 09:43 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/rest/MovieController.java
> +        if(filters == null || filters.isEmpty()) {
This is looking good. Let's just move the if statement to the service. That way you don't need to overload the method and you keep the logic in the service. Just pass the filter to the service method and let it deal with it.

2024-10-31 09:44 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/rest/MovieController.java
> +        if (filters == null || filters.isEmpty()) {
Same here, move the if to the service method.

2024-10-31 09:47 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/service/MovieServiceImpl.java
> +        return new MovieDTO(movies, totalSize);
Might be good idea to overload the constructor so you have one that will take Page<Movie> so you don't need to unpack it every time you have pagination with movie endpoints.

2024-10-31 09:49 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/utils/FilterMovie.java
> +    public FilterMovie(Map<String, String> filters) {
final keyword

2024-10-31 10:14 UTC, ivanazirojevic-abh commented on cinemaapp_frontend/src/pages/Home.jsx
> +        const upcomingMovies = await movieService.getMovies({
Currently you are fetching from both apis and the second request has to wait for the first one. We want to have them run at the same time and not block each other. It should help with the loading wait time. 

```
useEffect(() => {
  const fetchAndProcessCurrentlyShowing  = async () => {
      const currentlyShowing = await movieService.getMovies({
          page: currentlyShowingPage,
          venueId: selectedVenueId,
        });
        
       setCurrentlyShowingMovies({
          movies: currentlyShowing.movies,
          totalSize: currentlyShowing.totalSize,
        });
  };

  const fetchAndProcessUpcomingMovies = async () => {
      const upcomingMovies = await movieService.getMovies({
          type: "upcoming",
          page: upcomingPage,
          venueId: selectedVenueId,
        });

      setUpcomingMovies({
          movies: upcomingMovies.movies,
          totalSize: upcomingMovies.totalSize,
        });
  };

  fetchAndProcessCurrentlyShowing();
  fetchAndProcessUpcomingMovies();
}, []);
```

2024-10-31 11:21 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/rest/MovieController.java
> +        final FilterMovie filterMovie = new FilterMovie(filters);
Please test what happens when no filter is sent. You might get a null pointer here.

2024-10-31 11:22 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/rest/MovieController.java
> +        final FilterMovie filterMovie = new FilterMovie(filters);
Same thing here. Make sure you don't get an error if filters is null

2024-10-31 11:41 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/service/MovieServiceImpl.java
> +        final Optional<Venue> venue = venueRepository.findById(filterMovie.getVenueId());
We don't know if the filter is venue or something else. Let's make a generateFilterSql method in the filter class which will return WHERE part of the query. Then in the JPA repository you can have a method like this
```
    @Override
    public Page<Movie> findMoviesByFilter(MovieFilter filter, Pageable pageable) {
        String baseQuery = "SELECT m FROM Movie m";
        String filterQuery = filter.toQueryString(); 

        String finalQuery = filterQuery.isEmpty() ? baseQuery : baseQuery + " WHERE " + filterQuery;

        Query query = entityManager.createQuery(finalQuery, Movie.class);
        query.setFirstResult((int) pageable.getOffset());
        query.setMaxResults(pageable.getPageSize());
        
        List<Movie> movies = query.getResultList();

        // Count for pagination
        Query countQuery = entityManager.createQuery(
            "SELECT COUNT(m) FROM Movie m" + (filterQuery.isEmpty() ? "" : " WHERE " + filterQuery)
        );
        long count = (long) countQuery.getSingleResult();

        return new PageImpl<>(movies, pageable, count);
    }
```

Be careful of how you create this in order to avoid sql injections. Please also investigate if there is a better way to implement custom query for filtering.

2024-10-31 11:50 UTC, ivanazirojevic-abh requested changes
Please make FilterMovie class return the filtering query and use it in the JPA repository to make a custom query.

2024-10-31 13:33 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/dto/MovieDTO.java
> +    public MovieDTO(Page<Movie> moviePage) {
final keyword

2024-10-31 13:40 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/repository/FilterMovieRepositoryImpl.java
> +            query.setParameter("venueId", filter.getVenueId());
This should by added when you use toQueryString(). FilterMovie class already contains those values. This method should only care about forming the query and not the logic of filtering.

2024-10-31 13:44 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/service/MovieServiceImpl.java
> +}
new line

2024-10-31 13:46 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/utils/FilterMovie.java
> +            predicates.add("p.venueId.id = :venueId");
You should fill these values right here, they are already present. You can make this method return Query class if it helps avoid sql injections.

2024-10-31 13:49 UTC, ivanazirojevic-abh commented on cinemaapp_frontend/src/services/venueService.js
> +  getAll: async (page = 0, size = 4) => {
We already have the getAll method in the apiService, you just need to modify it to take page and size parameters. It is common to have backend return everything if the size is 0 so you can set that as the default value.

2024-10-31 13:51 UTC, ivanazirojevic-abh commented on cinemaapp_frontend/src/pages/Home.jsx
> +      {console.log(venueCarousel)}
Remove console.logs here and anywhere else if you can find them in project. They are dev tools, they should not be in the final code.

2024-10-31 13:52 UTC, ivanazirojevic-abh commented on cinemaapp_frontend/src/pages/Home.jsx
> +      if (selectedVenueId) {
You can flip the condition to !selectedVenueId and return if true so you have less nesting.

2024-10-31 13:59 UTC, ivanazirojevic-abh requested changes
Fill in the filtering values in the FilterMovie class and not in the repository.

2024-10-31 14:49 UTC, ivanazirojevic-abh commented on cinemaapp_frontend/src/pages/Home.jsx
> +        venueList.totalSize
Now, here instead of waiting for the previous call, you can just get all of them by passing 0 as size. Please add the logic so they don't wait for each other the same way you did for line 45.

2024-10-31 14:55 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/utils/FilterMovie.java
> +            predicates.add("p.venueId.id = " + getVenueId());
For example if I send the request for this API and set the venueId to this value - "3; SELECT 'DROP DATABASE "' || datname || '";'
FROM pg_database
WHERE datistemplate = false
AND datname NOT IN ('postgres');"

Are you sure I'm not going to destroy your whole db?

2024-10-31 14:58 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/service/VenueServiceImpl.java
> +            List<Venue> allVenues = venueRepository.findAll();
final

2024-10-31 15:00 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/service/MovieServiceImpl.java
> +        final List<Movie> currentlyShowingMovies = moviePage.getContent().stream()
We don't want in memory filtering. Please add this to the query.

2024-10-31 15:01 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/service/MovieServiceImpl.java
> +        final List<Movie> currentlyShowingMovies = moviePage.getContent().stream()
You can add date fields to the filter.

2024-10-31 15:04 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/service/MovieServiceImpl.java
> +        final List<Movie> upcomingMovies = moviePage.getContent().stream()
Same here, add dates to the filter.

2024-10-31 15:57 UTC, ivanazirojevic-abh commented on cinemaapp_backend/src/main/java/com/abhinternship/CinemaApp/utils/FilterMovie.java
> +            parameters.add(projectionEndDate);
Let's leave this as is now, but we might have to change it later on.

2024-10-31 16:01 UTC, ivanazirojevic-abh commented on cinemaapp_frontend/src/pages/Home.jsx
> +      if (selectedVenueId) return;
Wasn't the condition like this before? Are you sure this works? I don't see the negation.

2024-10-31 16:02 UTC, seomasha commented on cinemaapp_frontend/src/pages/Home.jsx
> +      if (selectedVenueId) return;
misspell :D

2024-10-31 16:03 UTC, ivanazirojevic-abh approved these changes
Please see last two comments, they are just observations and might not need any changes. You can merge the PR after that. Excellent work, Sead!

2024-10-31 16:04 UTC, merged